### ISSUE TITLE
Syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by seanywang0408** [godweiyang/GrabGPU#1]
I tried all three version of gg in two different machines and got the following error:

``` bash
./gg_cu110: line 7: syntax error near unexpected token `newline'
./gg_cu110: line 7: `<!DOCTYPE html>'
```

Not sure what is wrong.

**Comment by godweiyang** [comment]
> I tried all three version of gg in two different machines and got the following error:
> 
> ```shell
> ./gg_cu110: line 7: syntax error near unexpected token `newline'
> ./gg_cu110: line 7: `<!DOCTYPE html>'
> ```
> 
> Not sure what is wrong.

Sorry. I have updated the download link. Try again please.
